### ISSUE TITLE
Unmodified VxKex

### ISSUE THREAD

**Issue by techguy16** [commandcontrolQ/VxKex#1]
I have a copy of what I believe is an unmodified VxKex installer. It does contain files marked March 19th 2024, the day VxKex 1.1.1.1375 was released. It's attached if you want to verify the authenticity.

[KexSetup_Release_1_1_1_1375.zip](https://github.com/user-attachments/files/16925972/KexSetup_Release_1_1_1_1375.zip)

**Comment by commandcontrolQ** [comment]
Hi,

Thanks for providing an unmodified installer!
I will check their hashes soon.

~ commandControlQ

**Comment by techguy16** [comment]
I do have some older releases of VxKex if you would like them. I think I've only got 1.1.0.1291, 1.0.0.999 and 0.0.0.2.

**Comment by commandcontrolQ** [comment]
Apologies for the late response - if you could send those to me, that would be great! Please refer to the contact info on my GitHub profile.
